# Generated by Django 4.2.6 on 2023-11-01 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0045_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact_information', models.TextField()),
                ('academic_qualifications', models.TextField()),
                ('application_status', models.CharField(choices=[('Applied', 'Applied'), ('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publishDate', models.DateField()),
                ('downloadUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('website', models.URLField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_deadline', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.university')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('Admitted', 'Admitted'), ('Rejected', 'Rejected'), ('Waitlisted', 'Waitlisted')], max_length=255)),
                ('waitlist_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.applicant')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.course')),
            ],
        ),
    ]
