# Generated by Django 4.2.6 on 2023-11-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_remove_applicationdeadline_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('seat_available', models.BooleanField(default=True)),
                ('admission_curriculum', models.TextField()),
            ],
        ),
    ]
