# Generated by Django 4.2.6 on 2023-11-01 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0049_seatavailability_delete_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatavailability',
            old_name='available_seats',
            new_name='Available_seats',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='due_time',
            new_name='Due_time',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='university_name',
            new_name='University_name',
        ),
    ]
