# Generated by Django 4.2.6 on 2023-11-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0050_rename_available_seats_seatavailability_available_seats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatavailability',
            old_name='Available_seats',
            new_name='AvailableSeats',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='Due_time',
            new_name='DueTime',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='University_name',
            new_name='UniversityName',
        ),
    ]
