# Generated by Django 4.2.6 on 2023-11-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0051_rename_available_seats_seatavailability_availableseats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publishDate', models.DateField()),
            ],
        ),
    ]
