# Generated by Django 4.2.6 on 2023-11-01 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0052_importantnotice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprimarydetails',
            old_name='UserImageFilename',
            new_name='UserImageFile',
        ),
    ]
