# Generated by Django 4.2.6 on 2023-11-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0053_rename_userimagefilename_usersprimarydetails_userimagefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantNotice',
        ),
        migrations.DeleteModel(
            name='SeatAvailability',
        ),
    ]
