# Generated by Django 4.2.6 on 2023-11-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0054_delete_importantnotice_delete_seatavailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('sl', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('due_time', models.DateTimeField()),
                ('available_seats', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='usersprimarydetails',
            old_name='UserImageFile',
            new_name='UserImageFilename',
        ),
    ]
