# Generated by Django 4.2.6 on 2023-11-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0055_importantnotice_seatavailability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatavailability',
            old_name='available_seats',
            new_name='AvailableSeats',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='due_time',
            new_name='DueTime',
        ),
        migrations.RenameField(
            model_name='seatavailability',
            old_name='university_name',
            new_name='UniversityName',
        ),
    ]
