# Generated by Django 4.2.6 on 2023-11-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0056_rename_available_seats_seatavailability_availableseats_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprimarydetails',
            old_name='UserImageFilename',
            new_name='UserImageFile',
        ),
    ]
