# Generated by Django 4.2.6 on 2023-11-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0057_rename_userimagefilename_usersprimarydetails_userimagefile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importantnotice',
            old_name='publish_date',
            new_name='Publish_date',
        ),
        migrations.RenameField(
            model_name='importantnotice',
            old_name='sl',
            new_name='Serial',
        ),
        migrations.RenameField(
            model_name='importantnotice',
            old_name='title',
            new_name='Title',
        ),
    ]
