# Generated by Django 4.2.6 on 2023-11-01 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0058_rename_publish_date_importantnotice_publish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersprimarydetails',
            old_name='UserImageFile',
            new_name='UserImageFilename',
        ),
    ]
