# Generated by Django 4.2.6 on 2023-11-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0061_collage_honours_masters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('facility', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
