# Generated by Django 4.2.6 on 2023-11-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0063_book_bus_userb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=2),
            preserve_default=False,
        ),
    ]
