# Generated by Django 4.2.6 on 2023-11-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0064_bus_bus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='busid',
        ),
        migrations.RemoveField(
            model_name='book',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
